apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 80
      nodePort: {{ .Values.service.httpNodePort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.dnsPort }}
      targetPort: 53
      nodePort: {{ .Values.service.dnsNodePort }}
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.dnsPort }}
      targetPort: 53
      nodePort: {{ .Values.service.dnsNodePort }}
      protocol: UDP
      name: dns-udp
  selector:
    app: pihole