apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.dnsPort }}
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.dnsPort }}
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app: pihole